## Auto deploy with auto tag release when pushed to main branch

name: Build and Push to AWS ECR
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
permissions:
  contents: write 
jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: tag-release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to Private Amazon ECR
        run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          TAG=${{ steps.get-latest-tag.outputs.tag }}
          docker build \
          --no-cache \
          -t $ECR_REGISTRY:latest .
          docker tag $ECR_REGISTRY:latest $ECR_REGISTRY:$TAG
          docker push $ECR_REGISTRY:$TAG
  Deploy:
    name: Deploy on Production
    runs-on: ubuntu-latest
    needs: [tag-release, build-and-push]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
             sh /home/ubuntu/login-aws.sh
             sleep 10
             cd /home/ubuntu/nepalvoice-deployment
             export RELEASE_TAG=${{ steps.get-latest-tag.outputs.tag }}
             docker pull <aws-id>.dkr.ecr.ap-southeast-1.amazonaws.com/safeweb:$RELEASE_TAG
             RELEASE_TAG=${RELEASE_TAG}  docker compose up -d
