# GitHub Actions Workflow: Auto Deploy with Auto Tag Release
# Automatically tags releases, builds Docker images, pushes to AWS ECR, and deploys on push to main branch

# Workflow name
name: Build and Push to AWS ECR

# Trigger on push to main branch
on:
  push:
    branches:
      - main

# Global environment variables
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

# Required permissions
permissions:
  contents: write

jobs:
  # Job to create and push a new semantic version tag
  tag-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Get the latest existing tag
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true

      # Bump semantic version based on current tag
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}

      # Push the new tag to repository
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

  # Job to build and push Docker image to ECR
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: tag-release

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Get the latest tag (created by previous job)
      - name: Get the latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true

      # Configure AWS credentials for ECR access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Log in to Private Amazon ECR
        run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Build, tag, and push Docker image
      - name: Build, tag, and push image to Amazon ECR
        run: |
          TAG=${{ steps.get-latest-tag.outputs.tag }}
          docker build \
          --no-cache \
          -t $ECR_REGISTRY:latest .
          docker tag $ECR_REGISTRY:latest $ECR_REGISTRY:$TAG
          docker push $ECR_REGISTRY:$TAG

  # Job to deploy to production server
  Deploy:
    name: Deploy on Production
    runs-on: ubuntu-latest
    needs: [tag-release, build-and-push]
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Get the latest tag for deployment
      - name: Get the latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: v0.0.0
          with_initial_version: true

      # Configure AWS credentials for deployment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy to production server via SSH
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
             sh /home/ubuntu/login-aws.sh
             sleep 10
             cd /home/ubuntu/deployment
             export RELEASE_TAG=${{ steps.get-latest-tag.outputs.tag }}
             RELEASE_TAG=${RELEASE_TAG}  docker compose up -d
